### PR TITLE
Include timestamp when printing news item

### PR DESCRIPTION
**Pull request by codeclem**
This adds the date and time the news item was published to the output of the 'read' subcommand.

### CODE REVIEW

**Comment by codeclem** [comment]
Sorry about the messy PR, it's my first.

The second commit adds a right-aligned timestamp to the list of news item titles, wrapping the title as needed. For example:
```
$ ./informant list
0: rsync compatibility                                                     Wed, 15 Jan 2020 20:14:43 +0000
1: Now using Zstandard instead of xz for package compression               Sat, 04 Jan 2020 20:35:55 +0000
2: Xorg cleanup requires manual intervention                               Fri, 20 Dec 2019 13:37:40 +0000
3: primus_vk>=1.3-1 update requires manual intervention                    Mon, 25 Nov 2019 13:03:45 +0000
4: New kernel packages and mkinitcpio hooks                                Sun, 10 Nov 2019 21:41:24 +0000
5: Clarification regarding recent email activity on the arch-announce list Fri, 25 Oct 2019 20:27:46 +0000
6: Required update to recent libarchive                                    Wed, 16 Oct 2019 12:43:54 +0000
7: `base` group replaced by mandatory `base` package - manual intervention Sun, 06 Oct 2019 10:09:12 +0000
required
8: astyle>=3.1-2 update requires manual intervention                       Mon, 26 Aug 2019 06:39:08 +0000
9: tensorflow>=1.14.0-5 update requires manual intervention                Tue, 20 Aug 2019 22:22:17 +0000
```

**Comment by bradford-smith94** [comment]
Not sure why this didn't auto-detect, but it was merged.

**Comment by codeclem** [comment]
I had to make a last minute adjustment which didn't make it into the merge. https://github.com/bradford-smith94/informant/compare/2dd706222a354e82c7d38824aa075c261883f6f4..21c13152e54b817aa131af85a41199c09fc21150

**Comment by bradford-smith94** [comment]
Oh, my bad, will re-merge.

**Pull request closed without merging**
